[tool.bump-my-version]
current_version = "0.1.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

# Enable Git tagging & commits
commit = true
message = "Bump version: {current_version} → {new_version}"
commit_args = ""
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"

# Hook support (optional)
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

# File-specific versioning
[[tool.bump-my-version.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bump-my-version.files]]
filename = "src/app/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
