---
name: cz_conventional_commits
version: 0.1.0
tag_format: v$version
update_changelog_on_bump: true
changelog_file: CHANGELOG.md
commit_parser: cz.conventional_commits
info:
  title: Conventional Commits
  description: Standardized commit format across stock-* repos
  message: 'Write your commit message using the prompts below:'
  example: 'feat(queue): support fallback from SQS to RabbitMQ'
  types:
    - type: feat
      description: A new feature
      emoji: ✨
    - type: fix
      description: A bug fix
      emoji: 🐛
    - type: chore
      description: Build process, tooling, maintenance
      emoji: 🔧
    - type: docs
      description: Documentation only changes
      emoji: 📝
    - type: refactor
      description: Code refactoring without behavior change
      emoji: ♻️
    - type: style
      description: Code formatting, whitespace, etc.
      emoji: 🎨
    - type: test
      description: Adding or updating tests
      emoji: ✅
    - type: ci
      description: CI/CD pipeline changes
      emoji: 🔁
    - type: build
      description: Changes to packaging/build system
      emoji: 📦
  scopes:
    # 🧠 Core Logic
    - pollers
    - config
    - vault
    - queue
    - main
    - metrics

    # 🧪 Quality
    - tests
    - lint
    - types

    # 🛠 Build & CI/CD
    - ci
    - docker
    - deps
    - docs
    - versioning

    # 📁 Repo / Template Maintenance
    - template
    - init
    - release
