# .prettierrc.yaml

printWidth: 120          # Matches yamllint line-length max
tabWidth: 2              # Matches yamllint indentation.spaces
useTabs: false
proseWrap: always
yamlBracketSpacing: true
