---
name: Validate Kubernetes YAML
# on: [push, pull_request]
on:
  workflow_dispatch:
jobs:
  validate-kubernetes-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeval
        run: |
          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          chmod +x kubeval
          mv kubeval /usr/local/bin/
      - name: Run kubeval
        run: kubeval **/*.yaml
