---
name: Apply Labels to Pull Request
on:
  pull_request_target:
    types: [opened, edited, synchronize]
jobs:
  apply-labels-to-pull-request:
    name: Apply Labels to Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Apply Labels Based on PR Changes
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
