name: ArgoCD Linting & Sync Check
on: [push, pull_request]

jobs:
  argocd-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd
      - name: Validate ArgoCD Application
        run: argocd app validate --file argocd/application.yaml
