name: Validate ArgoCD Manifests
on: [push, pull_request]

jobs:
  argocd-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Validate YAML Syntax
        uses: ibiqlik/action-yamllint@v3
      - name: Validate Kubernetes Schema
        uses: instrumenta/kubeval-action@master
        with:
          files: "argocd/**/*.yaml"
