---
name: Bandit Security Scan
on: [push, pull_request]
jobs:
  bandit-security-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run Bandit (code security with strict options)
        run: |
          bandit -r src/ -lll -iii -f txt -o bandit-report.txt

      # Optional SARIF upload if using GitHub Advanced Security
      # - name: Convert to SARIF and upload to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: bandit-report.sarif
