---
name: Bandit Security Scan
on: [push, pull_request]
jobs:
  bandit-security-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use a stable version (3.13 is not released)
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run Bandit (code security)
        run: bandit -r src/ -ll -iii
