name: Python Build & Install Check
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Build Tools
        run: pip install build
      - name: Build Package
        run: python -m build
      - name: Install Package
        run: pip install dist/*.whl
