---
name: Cleanup Old Releases
on:
  schedule:
    - cron: 0 0 1 * *  # 1st of every month
  workflow_dispatch:
permissions:
  contents: write
jobs:
  cleanup-old-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          for release_id in $(gh api repos/${{ github.repository }}/releases \
            -q '.[] | select(.created_at < "'$(date -d '30 days ago' --iso-8601=seconds)'") | .id'); do
            echo "Deleting release ID: $release_id"
            gh api --method DELETE repos/${{ github.repository }}/releases/$release_id
          done
