---
name: Cleanup Artifacts
on:
  schedule:
    - cron: 0 0 * * 0  # Every Sunday
  workflow_dispatch:
jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Old Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Deleting old artifacts..."
          for artifact_id in $(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
              | jq -r '.artifacts[] | select(.created_at < "'$(date -d '7 days ago' --iso-8601=seconds)'") | .id'); do
              echo "Deleting artifact ID: $artifact_id"
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
          done
