---
name: Cleanup Workflow Runs
on:
  schedule:
    - cron: 0 0 * * 0  # Every Sunday
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  delete-old-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Deleting old workflow runs..."
          for run_id in $(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" \
              | jq -r '.workflow_runs[] | select(.created_at < "'$(date -d '30 days ago' --iso-8601=seconds)'") | .id'); do
              echo "Deleting workflow run ID: $run_id"
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
