---
name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches: [main]
    paths: [docs/**, mkdocs.yml]
permissions:
  contents: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]
      - name: Build and Deploy
        run: |-
          mkdocs gh-deploy --force
