name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-security-scan.yml'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y trivy

      - name: Scan Docker Image
        run: |
          docker build -t test-image .
          trivy image --exit-code 1 --severity HIGH,CRITICAL test-image
