---
name: GitHub Actions Cleanup
on:
  schedule:
    - cron: 0 0 * * 0  # ✅ Runs every Sunday at midnight (UTC)
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  github-actions-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Delete Old Workflow Runs (Older than 30 Days)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching old workflow runs..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" \
              | jq -r '.workflow_runs[] | select(.created_at < "'$(date -d '30 days ago' --iso-8601=seconds)'") | .id' \
              | xargs -I {} curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/{}" || true
          echo "Old workflow runs deleted."
      - name: Delete Old Artifacts (Older than 7 Days)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching old artifacts..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
              | jq -r '.artifacts[] | select(.created_at < "'$(date -d '7 days ago' --iso-8601=seconds)'") | .id' \
              | xargs -I {} curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}" || true
          echo "Old artifacts deleted."
      - name: Delete Old Cache Entries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Fetching old caches..."
          gh cache list --repo ${{ github.repository }} | awk '{print $1}' | xargs -I {} gh cache delete {} || true
          echo "Old cache deleted."
