name: Helm Dry-Run Deployment
on: [push, pull_request]

jobs:
  helm-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Set Up Kubernetes (Kind)
        uses: helm/kind-action@v1
      - name: Install Helm Chart (Dry Run)
        run: helm install test-release helm/ --dry-run
