---
name: 🧼 Ignore File Consistency Check
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for overlap in ignore files
        run: |-
          echo "Checking .gitignore vs .dockerignore vs MANIFEST.in"
          grep -v '^#' .gitignore | sort > .tmp.gitignore
          grep -v '^#' .dockerignore | sort > .tmp.dockerignore || true
          grep -v '^#' MANIFEST.in | sort > .tmp.manifest || true
          echo "--- .gitignore not in .dockerignore:"
          comm -23 .tmp.gitignore .tmp.dockerignore || true
          echo "--- .gitignore not in MANIFEST.in:"
          comm -23 .tmp.gitignore .tmp.manifest || true
