---
name: 📚 License Checker
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install pip-licenses
      - run: pip-licenses --format=markdown --with-urls --output-file=licenses.md
      - uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: licenses.md
