name: MyPy Type Checking

on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install mypy

      - name: Run MyPy
        run: mypy src/
