name: Ruff Linting
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --fix .
