---
name: Secret Scanning
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: 0 3 * * 0  # weekly full scan on Sunday at 3 AM UTC
jobs:
  # 🧪 PR Diff Scan
  diff-scan:
    name: TruffleHog PR Diff Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog on PR diff
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}

  # 🔍 Full Repo Scan
  full-scan:
    name: TruffleHog Full Repo Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog on entire repo
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
