name: Secret Scanning

on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Scan for Secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: . # Scan the entire repo
