name: Sphynx Documentation Build

on: [push, pull_request]

jobs:
  sphynxdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html
