---
name: Validate Kustomize Overlays
# on:
#   pull_request:
#   push:
#     branches: [main]
on:
  workflow_dispatch:
jobs:
  validate-kustomize-overlays:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        overlay: [dev, prod]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin
      - name: Validate overlay ${{ matrix.overlay }}
        run: |-
          kustomize build k8s/overlays/${{ matrix.overlay }} | tee result.yaml | kubectl apply --dry-run=client -f -
