---
name: Validate YAML & JSON
on: [push, pull_request]
jobs:
  validate-yaml-and-json:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
      - name: Validate JSON
        run: |-
          FILES=$(find . -type f -name "*.json")
          if [ -n "$FILES" ]; then
            echo "$FILES" | xargs -n1 jq . > /dev/null
          else
            echo "✅ No JSON files found — skipping validation."
          fi
